version: '3'

services:
  proxy:
    build: ./nginx
    image: carlososuna86/certbot:proxy
    container_name: proxy
    environment:
      - DEBUG
      - SSL_DOMAIN
      - SSL_ADMIN
    volumes:
      - ./certs:/etc/nginx/certs
      - ./www:/var/www/letsencrypt
    links:
      - app:letsencrypt.devsidestory.com
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      letsencrypt.tutorial:

  letsencrypt:
    build: ./certbot
    image: carlososuna86/certbot:certbot
    container_name: certbot
    command: /bin/true
    environment:
      - DEBUG
      - SSL_DOMAIN
      - SSL_ADMIN
    volumes:
      - ./certs:/etc/letsencrypt
      - ./www:/var/www/letsencrypt
    networks:
      letsencrypt.tutorial:

  app:
    image: dockercloud/hello-world
    container_name: app
    restart: always
    expose:
      - "80"
    networks:
      letsencrypt.tutorial:

#volumes:
#  letsencrypt_certs: 
#   - type: bind
#     source: ./certs
#  letsencrypt_www: 
#   - type: bind
#     source: ./www

networks:
  letsencrypt.tutorial:
